---
version: '3.5'

services:
  auth-bot:
    hostname: green-bot
    image: green-bot
    container_name: green-bot
    build: .
    restart: unless-stopped
    environment:
    - TG_BOT_KEY=${TG_BOT_KEY}
    - AUTH_URL=${AUTH_URL}
    - API_KEY=${API_KEY}
